### ISSUE TITLE
LoRa Module Error -2

### ISSUE THREAD

**Issue by Robocoder9000** [sparkfunX/LoRa_1W_Breakout#1]
I've hooked up the transceiver to an Arduino Nano and a Sparkfun Redboard, with all SPI, ground, 3.3v, and 5v pins hooked up as well as d0 on a hardware reset pin and d1 on a digital pin. I was using 3.3v logic on the Redboard, and had 1k resistors on the Nano's logic lines as suggested under the product page by Nate. However, on both boards when I run the example code, I always get the same "Initializing ... failed, code -2" error. Am I missing anything? I've tried using the provided code as well as the example code from Radiolib, and the issue persists. What else could I try?

**Comment by Robocoder9000** [comment]
Ah, turns out my SDI and SDO pins were backwards.

**Comment by PaulZC** [comment]
Thanks for the update - glad that's working for you

**Comment by Robocoder9000** [comment]
Thanks! Quick question for you- I'm looking to boost the range of the system, I'm only getting around 500m as of now. Are there any software tricks I can try? I'm already at 20dbm boost power.
