### ISSUE TITLE
Ordering A Board

### ISSUE THREAD

**Issue by agieocean** [sparkfunX/LoRa_1W_Breakout#2]
I'm a bit new to open hardware so excuse the question but is the intention that I solder the components to the board myself or is there some info in this repo I could provide a fabricator so they know which components to order/where to put them on the board?

**Comment by nseidle** [comment]
You can either order an assembled/tested board from [us](https://www.sparkfun.com/products/18572) or you can have your own PCB made, and assemble one yourself. The goal of making the design open was so that others could start from 'known working' design.

**Comment by agieocean** [comment]
Thank you so much for your response.
